import type { Product } from "./types";

/**
 * Fallback catalog — shown if Supabase is unreachable or the table is empty.
 * The same list is seeded into the database by scripts/supabase-setup.
 */
export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: "1", slug: "ysl-libre", name: "يولي سان لوران ليبر", brand: "YSL", category: "women",
    price: 85, old_price: 95, size: "90 مل",
    description: "عطر الحرية الأيقوني بلمسة فرنسية جريئة، مزيج من اللافندر والبرتقال الفاتر مع فانيليا دافئة تدوم طويلاً.",
    notes_top: "برتقال ماندرين، لافندر", notes_heart: "زهر البرتقال", notes_base: "فانيليا، مسك أبيض",
    image_url: "/products/ysl-libre.svg", in_stock: true, featured: true,
  },
  {
    id: "2", slug: "ysl-black-opium", name: "يولي سان لوران بلاك أوبيم", brand: "YSL", category: "women",
    price: 80, old_price: null, size: "90 مل",
    description: "عطر ليلي آسر من القهوة السوداء والفانيليا المطلية باللمعان، للمرأة الغامضة والجذابة.",
    notes_top: "قهوة سوداء، زهر الكمثرى", notes_heart: "ياسمين أبيض", notes_base: "فانيليا، باتشولي",
    image_url: "/products/ysl-black-opium.svg", in_stock: true, featured: true,
  },
  {
    id: "3", slug: "ysl-l-homme", name: "يولي سان لوران لوم", brand: "YSL", category: "men",
    price: 75, old_price: null, size: "100 مل",
    description: "أناقة رجالية حديثة تجمع بين الحلو الفاتر والخشب الراقي، مناسب لكل الأوقات.",
    notes_top: "ليمون، جزر", notes_heart: "زهر البرتقال، إكليل الجبل", notes_base: "خشب الأرز، تونكا",
    image_url: "/products/ysl-l-homme.svg", in_stock: true, featured: false,
  },
  {
    id: "4", slug: "dg-light-blue", name: "دولتشي آند غابانا لايت بلو", brand: "D&G", category: "women",
    price: 70, old_price: null, size: "100 مل",
    description: "نفحات صقلية منعشة كنسيم البحر الأبيض المتوسط، التفاح السيقلي والخيزران مع عنبر دافئ.",
    notes_top: "تفاح سيقلي، سيدر", notes_heart: "خيزران، ياسمين", notes_base: "عنبر، مسك أبيض",
    image_url: "/products/dg-light-blue.svg", in_stock: true, featured: false,
  },
  {
    id: "5", slug: "dg-the-one", name: "دولتشي آند غابانا ذا وان", brand: "D&G", category: "women",
    price: 78, old_price: 85, size: "75 مل",
    description: "عطر شرقي فاخر من الليتشي والياسمين مع فانيليا وعنبر، مثالي للمناسبات المسائية.",
    notes_top: "ليتشي، فواكه ناعمة", notes_heart: "ياسمين، زنبق", notes_base: "فانيليا، عنبر، مسك",
    image_url: "/products/dg-the-one.svg", in_stock: true, featured: false,
  },
  {
    id: "6", slug: "dg-devotion", name: "دولتشي آند غابانا ديفوشن", brand: "D&G", category: "women",
    price: 88, old_price: null, size: "50 مل",
    description: "أحدث إصدارات D&G الفاخرة، كريمة الليمون الإيطالي مع فانيليا غنية في قارورة مذهّلة.",
    notes_top: "ليمون إيطالي", notes_heart: "برتقال، لافندر", notes_base: "فانيليا، حليب اللوز",
    image_url: "/products/dg-devotion.svg", in_stock: true, featured: true,
  },
  {
    id: "7", slug: "narciso-for-her", name: "نارسيسو رودريغيز فور هير", brand: "Narciso", category: "women",
    price: 72, old_price: null, size: "100 مل",
    description: "أيقونة الأنوثة الهادئة، مسك ناعم مع ورد وياسمين في تركيبة نظيفة وأنيقة.",
    notes_top: "أوسمانتوس، فانيليا", notes_heart: "مسك ناعم", notes_base: "فيتيفر، خشب الساج",
    image_url: "/products/narciso-for-her.svg", in_stock: true, featured: false,
  },
  {
    id: "8", slug: "narciso-poudree", name: "نارسيسو بودريه", brand: "Narciso", category: "women",
    price: 75, old_price: null, size: "90 مل",
    description: "عبير بودري فخم من الزهور البيضاء والمسك، نعومة تترك أثراً لا يُنسى.",
    notes_top: "زهور بيضاء", notes_heart: "مسك بودري", notes_base: "خشب الكشمير، فيتيفر",
    image_url: "/products/narciso-poudree.svg", in_stock: true, featured: false,
  },
  {
    id: "9", slug: "givenchy-linterdit", name: "جيفنشي لانترديت", brand: "Givenchy", category: "women",
    price: 82, old_price: 90, size: "80 مل",
    description: "عطر محرم بمعنى الكلمة: توبروز وياسمين داكنان على قاعدة فيتيفر وفانيليا جريئة.",
    notes_top: "برتقال، كمثرى", notes_heart: "ياسمين، توبروز", notes_base: "فيتيفر، باتشولي، فانيليا",
    image_url: "/products/givenchy-linterdit.svg", in_stock: true, featured: true,
  },
  {
    id: "10", slug: "givenchy-gentleman", name: "جيفنشي جينتلمان", brand: "Givenchy", category: "men",
    price: 70, old_price: null, size: "100 مل",
    description: "رجولية كلاسيكية بروح عصرية، عيدان الشمر والإيريس مع خشب دافئ وأنيق.",
    notes_top: "كمثرى، هيل", notes_heart: "إيريس، قرفة", notes_base: "فانيليا، باتشولي",
    image_url: "/products/givenchy-gentleman.svg", in_stock: true, featured: false,
  },
  {
    id: "11", slug: "cavalli-paradiso-azzurro", name: "روبرتو كافالي باراديسو أزورو", brand: "Roberto Cavalli", category: "women",
    price: 60, old_price: null, size: "75 مل",
    description: "نسيم متوسطي ساحر من الياسمين والبرغموت مع خشب أبيض، كأنه إجازة على الشاطئ.",
    notes_top: "برغموت، ليمون", notes_heart: "ياسمين، زهر البرتقال", notes_base: "خشب أبيض، مسك",
    image_url: "/products/cavalli-paradiso-azzurro.svg", in_stock: true, featured: false,
  },
  {
    id: "12", slug: "paco-olympia", name: "باكو رابان أولمبيا", brand: "Paco Rabanne", category: "women",
    price: 85, old_price: 95, size: "80 مل",
    description: "عطر الإلهة اليونانية، مملحة وخشبية مع فانيليا كريمية، جرأة وأنوثة لا تُقاوم.",
    notes_top: "جريب فروت، كمثرى", notes_heart: "ياسمين، زنبق الماء", notes_base: "فانيليا، مسك مملح",
    image_url: "/products/paco-olympia.svg", in_stock: true, featured: true,
  },
  {
    id: "13", slug: "paco-1-million", name: "باكو رابان ون مليون", brand: "Paco Rabanne", category: "men",
    price: 75, old_price: null, size: "100 مل",
    description: "الذهب السائل، قرفة وورد مع جلد وفانيليا، حضور لا يمرّ دون أثر.",
    notes_top: "برغموت، نعناع", notes_heart: "قرفة، ورد", notes_base: "جلد، فانيليا، عود",
    image_url: "/products/paco-1-million.svg", in_stock: true, featured: false,
  },
  {
    id: "14", slug: "juicy-viva-la-juicy-set", name: "طقم جوسي كوتور فيفا لا جوسي", brand: "Juicy Couture", category: "gift",
    price: 65, old_price: 75, size: "100 مل + لوشن + 10 مل",
    description: "طقم هدايا فاخر: عطر فيفا لا جوسي مع لوشن الجسم وحافظة جيب، هدية مثالية لكل مناسبة.",
    notes_top: "ويلد بيري، ماندرين", notes_heart: "زهرة هونيسكل، جاردينيا", notes_base: "فانيليا، كراميل، براليه",
    image_url: "/products/juicy-viva-la-juicy-set.svg", in_stock: true, featured: true,
  },
  {
    id: "15", slug: "chanel-bleu", name: "شانيل بلو دي شانيل", brand: "Chanel", category: "men",
    price: 110, old_price: null, size: "100 مل",
    description: "أيقونة الرجال الفرنسية، حمضيات وخشب الصندل مع لبان ومسك، عميق وأنيق.",
    notes_top: "جريب فروت، نعناع", notes_heart: "جوزة الطيب، فلفل", notes_base: "صندل، لبان، سيدر",
    image_url: "/products/chanel-bleu.svg", in_stock: true, featured: true,
  },
  {
    id: "16", slug: "chanel-coco-mademoiselle", name: "شانيل كوكو مادموزيل", brand: "Chanel", category: "women",
    price: 115, old_price: null, size: "100 مل",
    description: "جرأة كلاسيكية من البرتقال والورد الدمشقي مع باتشولي فخم، توقيع المرأة الراقية.",
    notes_top: "برتقال، برغموت", notes_heart: "ورد دمشقي، ياسمين", notes_base: "باتشولي، فيتيفر",
    image_url: "/products/chanel-coco-mademoiselle.svg", in_stock: true, featured: false,
  },
  {
    id: "17", slug: "jpg-le-male", name: "جان بول غوتييه لو مال", brand: "Jean Paul", category: "men",
    price: 70, old_price: null, size: "125 مل",
    description: "الأسطورة الوردية، لافندر ونعناع مع فانيليا دافئة، عطر رجالي خالد منذ التسعينات.",
    notes_top: "نعناع، لافندر", notes_heart: "قرفة، كمثرى", notes_base: "فانيليا، توباكو",
    image_url: "/products/jpg-le-male.svg", in_stock: true, featured: false,
  },
  {
    id: "18", slug: "elie-saab-le-parfum", name: "إيلي صعب لو بارفان", brand: "Elie Saab", category: "women",
    price: 68, old_price: null, size: "90 مل",
    description: "فخامة لبنانية عالية: زهر البرتقال مع ياسمين وورد، أناقة قادمة من منصات العرض.",
    notes_top: "زهر البرتقال", notes_heart: "ياسمين، ورد", notes_base: "باتشولي، عنبر، مسك",
    image_url: "/products/elie-saab-le-parfum.svg", in_stock: true, featured: false,
  },
  {
    id: "19", slug: "versace-eros", name: "فيرساتشي إيروس", brand: "Versace", category: "men",
    price: 72, old_price: null, size: "100 مل",
    description: "عطر الحب والرغبة، نعناع وتفاح أخضر مع فانيليا وتونكا، حيوية وجاذبية.",
    notes_top: "نعناع، تفاح أخضر", notes_heart: "بلسم النعناع، جيرانيوم", notes_base: "فانيليا، تونكا، سيدر",
    image_url: "/products/versace-eros.svg", in_stock: true, featured: false,
  },
  {
    id: "20", slug: "lancome-la-vie-est-belle", name: "لانكوم لا في إي بيل", brand: "Lancôme", category: "women",
    price: 90, old_price: 100, size: "100 مل",
    description: "الحياة جميلة، إيريس وبراليات حلوة مع باتشولي، ابتسامة في قارورة كريستالية.",
    notes_top: "كشمش أسود، كمثرى", notes_heart: "إيريس، ياسمين", notes_base: "براليه، باتشولي، تونكا",
    image_url: "/products/lancome-la-vie-est-belle.svg", in_stock: true, featured: false,
  },
  {
    id: "21", slug: "hugo-boss-bottled", name: "هوغو بوس بوتلد", brand: "Hugo Boss", category: "men",
    price: 65, old_price: null, size: "100 مل",
    description: "عطر الرجل الناجح، تفاح وقرفة مع صندل وفانيليا، كلاسيكي للمكتب والمناسبات.",
    notes_top: "تفاح، برغموت", notes_heart: "قرفة، جيرانيوم", notes_base: "صندل، فيتيفر، فانيليا",
    image_url: "/products/hugo-boss-bottled.svg", in_stock: true, featured: false,
  },
  {
    id: "22", slug: "marc-jacobs-daisy", name: "مارك جاكوبس ديزي", brand: "Marc Jacobs", category: "women",
    price: 70, old_price: null, size: "100 مل",
    description: "انتعاش كرومي من البنفسج والفراولة مع خشب أبيض، شبابية وبهجة يومية.",
    notes_top: "بنفسج، فراولة", notes_heart: "ياسمين، جاردينيا", notes_base: "خشب أبيض، مسك",
    image_url: "/products/marc-jacobs-daisy.svg", in_stock: true, featured: false,
  },
];
